In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('støtte_modtagere_2014.csv', encoding='latin-1', delimiter=';')
df.head()

,Navn,Kommune,Postnr,Region,Measure,EU(DKK),National(DKK),Sum(DKK),Totalt(DKK),Unnamed: 9
0,[Anonym - 19690],Egedal Kommune,3650,Region Hovedstaden,(b)measures aimed at restructuring and develop...,-541.851,-541.851,-1.083.702,-1.083.702,NaN
1,[Anonym - 18098],Morsø Kommune,7900,Region Nordjylland,(c),-160.000,-160.000,-320.000,-320.000,NaN
2,[Anonym - 18139],510,6510,Region Syddanmark,(a) measures targeting the sustainable use of ...,-99.225,-81.184,-180.408,-180.408,NaN
3,[Anonym - 18759],Rebild Kommune,9500,Region Nordjylland,(c),-54.156,-54.156,-108.313,-108.313,NaN
4,[Anonym - 18329],350,4060,Region Sjælland,-,-1.392,0.000,-1.392,-57.017,NaN

In [8]:
df.dtypes

Navn              object
Kommune           object
Postnr             int64
Region            object
Measure           object
EU(DKK)          float64
National(DKK)    float64
Sum(DKK)          object
Totalt(DKK)       object
Unnamed: 9       float64
dtype: object

In [12]:
import re
from slugify import slugify

NUM_RE = re.compile('\[Anonym - (\d+)\]')
get_id = lambda x: NUM_RE.match(x).group(1)
df['recipient_id'] = df.apply(lambda x: 'DK-%s' % get_id(x['Navn']) if x['Navn'].startswith('[Anonym - ') else
                                        'DK-%s-%s' % (x['Postnr'], slugify(x['Navn'])), 1)
df['Navn'] = df['Navn'].apply(lambda x: '' if x.startswith('[Anonym - ') else x)
df.head()

,Navn,Kommune,Postnr,Region,Measure,EU(DKK),National(DKK),Sum(DKK),Totalt(DKK),Unnamed: 9,recipient_id
0,,Egedal Kommune,3650,Region Hovedstaden,(b)measures aimed at restructuring and develop...,-541.851,-541.851,-1.083.702,-1.083.702,NaN,DK-19690
1,,Morsø Kommune,7900,Region Nordjylland,(c),-160.000,-160.000,-320.000,-320.000,NaN,DK-18098
2,,510,6510,Region Syddanmark,(a) measures targeting the sustainable use of ...,-99.225,-81.184,-180.408,-180.408,NaN,DK-18139
3,,Rebild Kommune,9500,Region Nordjylland,(c),-54.156,-54.156,-108.313,-108.313,NaN,DK-18759
4,,350,4060,Region Sjælland,-,-1.392,0.000,-1.392,-57.017,NaN,DK-18329

In [13]:
df['recipient_location'] = df.apply(lambda x: '%s, %s' % (x['Kommune'], x['Region']), 1)

df = df.rename(columns={
    'Navn': 'recipient_name',
    'Postnr': 'recipient_postcode',
    'Measure': 'scheme',
    'EU(DKK)': 'amount'
})

df['currency'] = 'DKK'
df['country'] = 'DK'
df['year'] = 2014
df.head()

,recipient_name,Kommune,recipient_postcode,Region,scheme,amount,National(DKK),Sum(DKK),Totalt(DKK),Unnamed: 9,recipient_id,recipient_location,currency,country,year
0,,Egedal Kommune,3650,Region Hovedstaden,(b)measures aimed at restructuring and develop...,-541.851,-541.851,-1.083.702,-1.083.702,NaN,DK-19690,"Egedal Kommune, Region Hovedstaden",DKK,DK,2014
1,,Morsø Kommune,7900,Region Nordjylland,(c),-160.000,-160.000,-320.000,-320.000,NaN,DK-18098,"Morsø Kommune, Region Nordjylland",DKK,DK,2014
2,,510,6510,Region Syddanmark,(a) measures targeting the sustainable use of ...,-99.225,-81.184,-180.408,-180.408,NaN,DK-18139,"510, Region Syddanmark",DKK,DK,2014
3,,Rebild Kommune,9500,Region Nordjylland,(c),-54.156,-54.156,-108.313,-108.313,NaN,DK-18759,"Rebild Kommune, Region Nordjylland",DKK,DK,2014
4,,350,4060,Region Sjælland,-,-1.392,0.000,-1.392,-57.017,NaN,DK-18329,"350, Region Sjælland",DKK,DK,2014

In [15]:
df = df.drop(['Kommune', 'Region', 'National(DKK)', 'Sum(DKK)', 'Totalt(DKK)', 'Unnamed: 9'], 1)
df.head()

,recipient_name,recipient_postcode,scheme,amount,recipient_id,recipient_location,currency,country,year
0,,3650,(b)measures aimed at restructuring and develop...,-541.851,DK-19690,"Egedal Kommune, Region Hovedstaden",DKK,DK,2014
1,,7900,(c),-160.000,DK-18098,"Morsø Kommune, Region Nordjylland",DKK,DK,2014
2,,6510,(a) measures targeting the sustainable use of ...,-99.225,DK-18139,"510, Region Syddanmark",DKK,DK,2014
3,,9500,(c),-54.156,DK-18759,"Rebild Kommune, Region Nordjylland",DKK,DK,2014
4,,4060,-,-1.392,DK-18329,"350, Region Sjælland",DKK,DK,2014

In [18]:
len(df)

100000

In [19]:
df['amount'].sum()

3720265.0859999997